# Generated by Django 3.2.5 on 2021-11-26 11:07

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
