# Generated by Django 3.2.5 on 2021-11-19 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default='club', max_length=50)),
                ('authorization', models.CharField(choices=[('AP', 'Applicant'), ('ME', 'Member'), ('OF', 'Officer'), ('OW', 'Owner')], default='AP', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'club_name')},
            },
        ),
    ]
