# Generated by Django 3.2.5 on 2021-11-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Club',
            new_name='Club_Member',
        ),
    ]
