# Generated by Django 3.2.5 on 2021-11-23 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_club_club_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinclub', to=settings.AUTH_USER_MODEL),
        ),
    ]
